apiVersion: v1
kind: Service
metadata:
  generateName: flask-service-
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: flask-
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask 
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: 065603381703.dkr.ecr.us-west-2.amazonaws.com/devops-repo:1.0
        ports:
        - containerPort: 8000
